### ISSUE TITLE
WP config not found

### ISSUE THREAD

**Issue by filiptronicek** [luizbills/gitpod-wordpress#14]
When executing and getting into the GitPod interface, this error appears in the command line:
```bash
Success: WordPress downloaded.
cp: cannot stat '/home/gitpod/gitpod-wordpress/conf/wp-config.php': No such file or directory
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
Downloading Adminer ...
Creating phpinfo() page ...
Creating project files ...
Done!
```

**Comment by luizbills** [comment]
Try to build again. Just create another workspace.
I just did it and worked.

**Comment by filiptronicek** [comment]
Tried that, still here
![image](https://user-images.githubusercontent.com/29888641/106381896-2e7ede80-63bc-11eb-95d8-8c49b4d1a0c6.png)

**Comment by luizbills** [comment]
Are you creating a workspace of this repository?
If not, are you make changes in your fork?

**Comment by filiptronicek** [comment]
Yes, I am working on a project of mine.
Here is the config file of mine: https://github.com/MicrosoftSTC/stcblog/blob/wp-gitpod/.gitpod.Dockerfile
It shouldn't be much different except for a couple of path changes.

**Comment by luizbills** [comment]
You don't need change any path. Just copy the original `.gitpod.dockerfile`. Follow the README: https://github.com/luizbills/gitpod-wordpress#install

**Comment by filiptronicek** [comment]
Ok, I will try that, but the workspace directory is not always `/home/gitpod/gitpod-wordpress`, right? 
![image](https://user-images.githubusercontent.com/29888641/106428637-95a69c80-6469-11eb-944f-4f58886ccb2e.png)

**Comment by luizbills** [comment]
The workspace always is `/home/gitpod`. The `gitpod-wordpress` folder is deleted after. The root is always `public_html` (with your Wordpress installation)

**Comment by filiptronicek** [comment]
Okay, thanks, changed that, but it maybe seems like it's not being able to identify WP now? Pretty weird
```bash
Awaiting port 3306... ok
Please, wait ...
Creating MySQL user and database ...
Installing WordPress ...
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php:195
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php(195): implode()
#1 phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests.php(379): Requests_Transport_fsockopen->request()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(681): Requests::request()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php(310): WP_CLI\Utils\http_request()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php(319): Core_Command::read()
#5 phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php(183): Core_Command->get_download_offer()
#6 [internal function]: Core_Command->download()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func()
#8 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}()
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(451): call_user_func()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(371): WP_CLI\Dispatcher\Subcommand->invoke()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(394): WP_CLI\Runner->run_command()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(87): WP_CLI\Runner->run_command_and_exit()
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1102): WP_CLI\Runner->do_early_invoke()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process()
#16 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#17 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('...')
#18 /usr/local/bin/wp(4): include('...')
#19 {main}
  thrown in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php on line 195
Error: This does not seem to be a WordPress installation.
Pass --path=`path/to/wordpress` or run `wp core download`.
Downloading Adminer ...
Creating phpinfo() page ...
Creating project files ...
Done!
```
When I go to :8080 I get a 403 Forbidden.

**Comment by luizbills** [comment]
This error is because wp-cli is not compatible with PHP 8. I'm working in a workaround.

**Comment by luizbills** [comment]
Seems fixed now. Just copy the latest [.gitpod.dockerfile](https://github.com/luizbills/gitpod-wordpress/blob/master/.gitpod.dockerfile)

**Comment by filiptronicek** [comment]
Sure, I will check.

**Comment by filiptronicek** [comment]
Awesome, works now, thank you so much!
